### ISSUE TITLE
Modificar texto contacto

### ISSUE THREAD

**Issue by maritrinez** [medialab-prado/3tpd-asilo-ue#13]
Sustituir por
'Si tienes quieres saber más sobre el proyecto, publicarlo o colaborar con nosotros, escríbenos a:'

**Comment by MarianBlanco** [comment]
¿Cómo veis que en lugar de "Contacto" ponga "Quienes somos"? 

Bea el texto que has puesto se le ha colado un "tienes" :)

**Comment by elisagpaleo** [comment]
Iba a decir lo mismo sobre la errata.

Yo si eso pondría SOMOS... es que va a quedar muy largo, el menú está lleno de botones!!

**Comment by maritrinez** [comment]
Modificado el texto del contacto.

Abro otra issue para la cuestión del menú.

**Comment by soletommyo** [comment]
Me parece perfecto!

2016-02-11 11:18 GMT+01:00 Beatriz Martínez notifications@github.com:
