### ISSUE TITLE
Adaptar gráfico visOrigin al de edad y sexo

### ISSUE THREAD

**Issue by maritrinez** [medialab-prado/3tpd-asilo-ue#14]

**Comment by maritrinez** [comment]
Primera versión con bugs

**Comment by maritrinez** [comment]
Estimados todos:

le he dado una vueltecilla a los gráficos, decidme qué os parece (colores aparte)

**Comment by elisagpaleo** [comment]
Gracias @maritrinez !

Yo los veo mucho mejor así la verdad ;-) Los miro con calma este finde pero están fetén, enhorabuena!

**Comment by MarianBlanco** [comment]
Hola @maritrinez 

¡Me gustan! Creo que se entienden mejor aunque me he apuntado algunas cosillas que he visto para que veas qué puede estar pasando o si se puede hacer: 

**1º Gráfico - SOLICITUDES:** Austria da error (se corta), y después no aparece la línea de Dinamarca, Croacia, Letonia y Estonia. 
Sugerencia: ¿Se podría poner un punto o algo en el que al pasar el curso apareciera el % de cada año? Igual es una flipada jajaja!

**2º Gráfico- PAÍSES:** Me ha encantado, ahora con la diferencia de colores se entiende mucho mejor y es muy visual. Lo único que no entiendo son los huecos libres, ¿No hay datos o hay un error? Yo podría un hueco gris o algo que lo dijera como aparece en el gráfico de la edad. 

**3º Gráfico - EDAD:** Colores más diferentes, pero esto ya lo tenías apuntado ;) 

**4º Gráfico - SEXO**: El título está erróneo (está el de la edad) y dentro de los cuadritos pone "a favor undefined". Yo aquí recuperaría de alguna forma los porcentajes, por la diferencia era mínima y quizás podamos inducir a error. 

Sugerencia general para los cuadritos: Cambiar en la 2º pestaña "categoría" por "año", creo que se entiende mejor para el público en general, pero tampoco sé a qué se refiere la categoría y quizás estoy diciendo una tontería. 

Los miraré también desde la tablet y el móvil para ver cómo se ven.

**Comment by maritrinez** [comment]
> 1º Gráfico - SOLICITUDES: Austria da error (se corta), y después no aparece la línea de Dinamarca, Croacia, Letonia y Estonia. 

Arreglado. algunas líneas no están completas, es porque en los años que faltan, no hay datos.

> Sugerencia: ¿Se podría poner un punto o algo en el que al pasar el curso apareciera el % de cada año? Igual es una flipada jajaja!

No es imposible, pero me llevaría un poco de tiempo, que es algo que está empezando a faltarme. De todos modos, la intención de ese gráfico es ver tendencias, (o no tendencias en realidad) más que el dato exacto. Como orientación, están los ticks del eje de abscisas. Yo creo que suficiente.

> 2º Gráfico- PAÍSES: Me ha encantado, ahora con la diferencia de colores se entiende mucho mejor y es muy visual. Lo único que no entiendo son los huecos libres, ¿No hay datos o hay un error? Yo podría un hueco gris o algo que lo dijera como aparece en el gráfico de la edad.

Los huecos libres es que no hay datos para esa combinación de año y país. Los cuadraditos en gris de la edad no es que no se conozca el dato, si no que no se conoce la edad. Gente que llega con edad indefinida, y son aceptados más que el resto.

> 3º Gráfico - EDAD: Colores más diferentes, pero esto ya lo tenías apuntado ;)

he cambiado los colores, no sé qué versión has visto. pero no le voy a dar muchas más vueltas, que me vuelvo idiota. Si teneis sugerencias los cambio!

> 4º Gráfico - SEXO: El título está erróneo (está el de la edad

cierto, cambiado

> dentro de los cuadritos pone "a favor undefined". Yo aquí recuperaría de alguna forma los porcentajes, por la diferencia era mínima y quizás podamos inducir a error.

A mí me sale bien...
![captura de pantalla 2016-02-12 a las 12 20 08](https://cloud.githubusercontent.com/assets/3465542/13005569/08a78624-d183-11e5-8b82-3db3c6570252.png)

> Sugerencia  general para los cuadritos: Cambiar en la 2º pestaña "categoría" por "año", creo que se entiende mejor para el público en genera

Cambiado! mucho mejor

> Los miraré también desde la tablet y el móvil para ver cómo se ven.

mira mira, pero ya te digo yo que se ven mal.... tengo que arreglar eso que es una movida fina filipina
