### ISSUE TITLE
Destacados sección entrevistas

### ISSUE THREAD

**Issue by maritrinez** [medialab-prado/3tpd-asilo-ue#15]
Los textos a destacar se especifican en este [Google docs](https://docs.google.com/document/d/1mRK21RoFrw-MnL-uhPrjtbpchp21embhdotXUw_affc/edit?ts=56b7c297)

**Comment by MarianBlanco** [comment]
Hola!

Además de los destacados, viendo el texto pensé en las siguientes MEJORAS tanto de usabilidad como para llamar la atención: 
- Recuperar la idea de los titulares que pensamos al principio para hacerlas más atractiva y repetir la foto de cada persona también en cada página.
- Poner un botón de vuelta al comienzo de la página, o de vuelta a la página de expertos. 
- Añadir enlaces en el texto que enlacen con la parte legal y con los datos.

**Comment by MarianBlanco** [comment]
Hola chicxs!

¿Cómo va esta parte? Tengo preparadas ya otras entrevistas y me imagino que será mejor ya subirlas con el formato de destacados.

**Comment by ferblape** [comment]
Hola,

He estado a tope de curro, pero me he reservado este finde para hacerlo. Os
aviso el lunes.

2016-02-19 14:56 GMT+01:00 MarianBlanco notifications@github.com:

**Comment by ferblape** [comment]
Los destacados ya están subidos. De ese doc están todos los puntos excepto lo de enlazar al texto legal, que no sé muy bien a qué os referís.

Por favor, echad un vistazo y confirmad que está ok.

**Comment by MarianBlanco** [comment]
Le he echado un ojo rápidamente. La foto de la italiana sale muy grande no sé si será cosa del responsive porque estoy con la tablet.
Mañana te envío lo de los enlaces de legal y si hay que bajar algún destacado, aunque yo en especialistas (donde están todxs) pondría el titular directamente en lugar del cargo. No sé cómo quedaría...
¡Gracias por todo vuestro trabajo!

**Comment by MarianBlanco** [comment]
¿Cómo os mando las dos entrevistas nuevas? He estado esperando por si salía al final una que hemos mandado a Bélgica pero no he vuelto a tener noticias... Así que de momento son 2 no 4. 

Por otra parte no sé como hacer lo de los enlaces... ¿No hay una forma en la que yo pueda entrar al texto y editarlo para poner los enlaces directamente?

**Comment by maritrinez** [comment]
Los enlaces puedes especificarlos en un documento como el que hicisteis para las erratas. Una tabla en la que sea página(entrevista) - texto a enlazar - dirección del enlace.

En cuanto a las entrevistas nuevas, puedes hacerlo como lo hicimos con las otras, me las envío Elisa en un documento. Algo así https://docs.google.com/document/d/1E0clXrGIQe8Kx2iRx5PtjLGxNfYc1olHDzZtSrYZvxE/edit

**Comment by MarianBlanco** [comment]
Ok Bea! 
Ya están las dos entrevistas en la carpeta. Pero también te las paso aquí, los destacados los he subrayado en verde en el texto para que os sirva de orientación a la hora de ponerlos: 
[Caridad](https://docs.google.com/document/d/1E0clXrGIQe8Kx2iRx5PtjLGxNfYc1olHDzZtSrYZvxE/edit?usp=sharing)
[Raúl](https://docs.google.com/document/d/1tapw-P5AmIgy3UvE3SbgjbS_jyock1csX-6DbrdgwCk/edit?usp=sharing) 

Las fotos os las subo también en la carpeta.

**Comment by ferblape** [comment]
Pasadme las imágenes y las subo yo.

2016-02-26 22:55 GMT+01:00 MarianBlanco notifications@github.com:

**Comment by MarianBlanco** [comment]
@ferblape te las he mandado al correo ;)

**Comment by ferblape** [comment]
Listas
