### ISSUE TITLE
Mail/Formulario contacto

### ISSUE THREAD

**Issue by maritrinez** [medialab-prado/3tpd-asilo-ue#16]
@elisagpaleo planteaba dejar el formulario de contacto inicial, sin dirección de correo; También porque el nombre va a cambiar de proyecto.
@MarianBlanco sugiere dejar el mail porque considera un poco engorroso rellenar formulario.

Respondiendo, por lo visto habilitar el formulario (antes estaba, pero no funcionaba) es un poco movida, porque el mensaje tiene que ir a una base de datos, y de hacer el delivery del mail... (o algo así, no me he enterado muy bien) y no contamos con esa infraestructura.

Total, que dejamos la dirección de correo. Eso sí, cuando tengamos el nuevo nombre, podemos crear otra dirección con ese nombre.

**Comment by elisagpaleo** [comment]
Fenomenal @maritrinez , lo dejamos así ;)
