### ISSUE TITLE
Nombre dominio

### ISSUE THREAD

**Issue by maritrinez** [medialab-prado/3tpd-asilo-ue#17]
@flowsta @ferblape @elisagpaleo @MarianBlanco @Andror @soletommyo @Sergio-bugs 
(si me he dejado a alguien, mencionadle para que se de por aludido, por favor).

Estáis todos invitados a participar en el debate para llegar a tener un nombre para el proyecto y el dominio.

Por contextualizar, hemos pensado un poco, sin llegar a un dominio concreto, pero sí a unas características que nos gustaría que tuviera:
- Que contenga la palabra 'refugiado' o una parte de ella, algo que suene a 'refugiado'.
- Que refleje la idea de desigualdad. En este sentido también se barajó hablar de 'la ruleta del asilo', 'lotería del asilo', cosas así, pero tenían un componente azaroso que no nos acababa de convencer, pero os lo cuento como estímulo, por si acaso a partir de ahí os viene algo a la cabeza.
- no nos importa que esté en inglés o en español.

Por la misma razón os cuento los nombres que barajamos actualmente, aunque ninguno de ellos parece que nos convence al 100%:
ponteensulugar
rafflegees / rifagiados
refugiómetro

Creo que eso es todo, si me dejo algo, completadlo por favor. 
Merci

**Comment by MarianBlanco** [comment]
Hola! 
Por fin he conseguido volver a meterme en Github :)  Yo le he estado dando vueltas estas semanas al tema del dominio y he caído en ciertas cosas que creo que son importantes: 
- Lo del dominio en inglés siendo una web en español no lo veo... Si nuestro target es el público hispanohablante tiene que estar en español dado que en "Google" buscamos mayoritariamente en el idioma en el que esperamos encontrar la información. Además del SEO, si está en español es más fácil (y lógico) posicionarnos en esta lengua (o al menos intentarlo). 
- Al final no es un "observatorio" propiamente dicho, sino que es más bien una campaña de sensibilización. Por ello, yo optaría más por buscar un nombre de dominio sencillo, que se supiera de que hablamos con leerlo y contuviera la idea básica del proyecto pero que fuera más rollo campaña. 
- Luego tenemos el debate de que "asilo" parece de ancianos y "refugio" de montaña... pero bueno aquí poco podemos hacer. 
  Sobre los nombres que habíamos pensado se me ocurre también: 
- enellugardeunrefugiado.org
- buscandoasiloeneuropa.org
- buscandorefugio.org
- derechodeasilodesigual.org

No sé, ninguno me termina de convencer tampoco pero creo que es importante tener presente lo que he comentado. 

¡Madre mía no me extraña que la gente registre los nombres buenos! jajaja

**Comment by elisagpaleo** [comment]
En pocas palabras porque estoy en la ofi, las dos opciones que me gustan más son 

ponteensulugar.org

y

buscandorefugio.org

;)

**Comment by soletommyo** [comment]
Me parecen super acertadas tus reflexiones Marian!

yo opto por:

derechodeasilodesigual.org

o

buscandoasiloeneuropa.org (tal vez recortardolo a buscandoasiloeneu)

y: ponteensulugar.org tampoco lo descartaría

Claro está que será dificil que todos vayamos a acordarnos en lo mismo así
que me remito a lo que tenga mas aprobaciones!

besos

Mariasole

2016-02-11 11:08 GMT+01:00 elisagpaleo notifications@github.com:

**Comment by Andror** [comment]
refu-jungle no os moló nada, verdad?!

```
  From: Beatriz Martínez <notifications@github.com>
```

 To: medialab-prado/3tpd-asilo-ue 3tpd-asilo-ue@noreply.github.com 
Cc: Andror ortuonline@yahoo.com
 Sent: Thursday, February 11, 2016 10:12 AM
 Subject: [3tpd-asilo-ue] Nombre dominio (#17)

@flowsta @ferblape @elisagpaleo @MarianBlanco @Andror @soletommyo @Sergio-bugs 
(si me he dejado a alguien, mencionadle para que se de por aludido, por favor).Estáis todos invitados a participar en el debate para llegar a tener un nombre para el proyecto y el dominio.Por contextualizar, hemos pensado un poco, sin llegar a un dominio concreto, pero sí a unas características que nos gustaría que tuviera:   
- Que contenga la palabra 'refugiado' o una parte de ella, algo que suene a 'refugiado'.
- Que refleje la idea de desigualdad. En este sentido también se barajó hablar de 'la ruleta del asilo', 'lotería del asilo', cosas así, pero tenían un componente azaroso que no nos acababa de convencer, pero os lo cuento como estímulo, por si acaso a partir de ahí os viene algo a la cabeza.
- no nos importa que esté en inglés o en español.
  Por la misma razón os cuento los nombres que barajamos actualmente, aunque ninguno de ellos parece que nos convence al 100%:
  ponteensulugar
  rafflegees / rifagiados
  refugiómetroCreo que eso es todo, si me dejo algo, completadlo por favor. 
  Merci—

**Comment by flowsta** [comment]
Hola

Todas las propuestas me parecen larguísimas, inmanejables. Optaría por algo corto, conciso, directo, al estilo "themigrantfiles", y como decís, que contenga refugiados en vez de asilo por las connotaciones:
- sinrefugio
- enbuscadeasilo.net
- europasinrefugio.net
- dossier-refugiados.net
- refugioeneuropa.net

O que destaque alguna característica, como por ejemplo:
- 10000km.org,
- refugioderiesgo.org
- sinrefugio.club

O que apueste por una solución:
- derechoarefugio.org
- todosrefugiados.org

(No he comprobado que estén disponibles salvo sinrefugio.club)

**Comment by elisagpaleo** [comment]
Hola a todxs!!

Ayer Marian y yo comentamos el tema del dominio y el que más nos gusta es éste que proponía Adolfo: europasinrefugio (está disponible).

Qué os parece? Por nosotras lo cogemos ya!!

Abrazos

**Comment by soletommyo** [comment]
Por mi perfecto!!

2016-02-19 14:35 GMT+01:00 elisagpaleo notifications@github.com:

**Comment by maritrinez** [comment]
A mí me parece maravilloso!

**Comment by MarianBlanco** [comment]
Adjudicado y comprado: europasinrefugio.org
Ya me diréis que datos os tengo que dar ;) 
Al final ha quedado un nombre chulo y al gusto de todxs :) :) ¡qué emoción!

**Comment by elisagpaleo** [comment]
Yuju! Gracias a todxs!

**Comment by Andror** [comment]
great!!

```
  From: MarianBlanco <notifications@github.com>
```

 To: medialab-prado/3tpd-asilo-ue 3tpd-asilo-ue@noreply.github.com 
Cc: Andror ortuonline@yahoo.com
 Sent: Saturday, February 20, 2016 12:00 AM
 Subject: Re: [3tpd-asilo-ue] Nombre dominio (#17)

Adjudicado y comprado: europasinrefugio.org
Ya me diréis que datos os tengo que dar ;) 
Al final ha quedado un nombre chulo y al gusto de todxs :) :) ¡qué emoción!—

**Comment by ferblape** [comment]
Ya funciona el dominio: http://europasinrefugio.org y http://www.europasinrefugio.org

Cierro la issue.
