### ISSUE TITLE
Menú principal

### ISSUE THREAD

**Issue by maritrinez** [medialab-prado/3tpd-asilo-ue#18]
Se sugiere:
- sustituir 'contacto' por 'quienes somos' o por 'somos' que es más corto.
- Quizá podamos suprimir la opción 'portada' del menú, ya que va al mismo sitio que si pinchas en en el título 'EL ASILO EN LA UE: UN DERECHO DESIGUAL'

**Comment by MarianBlanco** [comment]
Tienes razón, me parece bien suprimir la opción "portada".

**Comment by MarianBlanco** [comment]
He pensado que para la opción "somos" sería bueno incluir un texto antes de los nombres  para que contextualice: 

Este proyecto nace dentro del III Taller de Periodismo de Datos de Medialab-Prado en 2015 (un laboratorio ciudadano de producción, investigación y difusión de proyectos culturales del Ayuntamiento de Madrid) cuyo objetivo es analizar situaciones de desigualdad a través de los datos. 

¿Es el derecho de asilo en la Unión Europea un derecho desigual? Esta es la pregunta a la que pretende responder este proyecto. Nuestro objetivo con europasinrefugio.org es mostrar la política de asilo y refugio llevada a cabo por los diferentes Estados miembros a través de los datos, para visibilizar las desigualdades que existen a la hora de acceder al derecho de asilo por parte de las personas solicitantes.

**Comment by maritrinez** [comment]
Se me antoja un poco largo.. yo lo dejaría en algo así, quizá con un tono
más contundente, pero de esta longitud

¿Es el derecho de asilo en la Unión Europea un derecho desigual?
Esta pregunta es el punto de partida de nuestro proyecto. En
europasinrefugio.org tratamos de visibilizar las desigualdades que existen
a la hora de acceder al derecho de asilo en los diferentes países de la UE.

**Comment by MarianBlanco** [comment]
Me parece bien. Se me ocurre que se puede enlazar la palabra proyecto con la web del Medialab del proyecto para que se entienda un poco cómo surge http://medialab-prado.es/article/explorando-la-desigualdad-proyectos-seleccionados#sexto

**Comment by maritrinez** [comment]
- [x] eliminar la opción de menú 'portada'
- [x] cambiar el literal 'contacto' por 'somos'
- [ ] modificar texto introductorio

**Comment by maritrinez** [comment]
He modificado el texto introductorio de la página 'somos'.
Mirad a ver qué os parece, en cuanto esté el definitivo, cerramos esta issue y a otra cosa mariposa

**Comment by elisagpaleo** [comment]
A mí me gusta mucho así @maritrinez . Qué opinas @MarianBlanco ?

**Comment by MarianBlanco** [comment]
Sii!! Esta muy bien, también lo de que al pasar se ponga rojo así da la idea de que estás realmente clicando.
