### ISSUE TITLE
Responsive home

### ISSUE THREAD

**Issue by maritrinez** [medialab-prado/3tpd-asilo-ue#20]

**Comment by MarianBlanco** [comment]
No sé cómo va el responsive pero si os sirve de ayuda en el móvil se apelotona el menú y el texto se sale de los botones.

**Comment by maritrinez** [comment]
esto va parado. El chico que nos estaba ayudando está desaparecido, yo esta semana no le he podido dedicar ni un minuto

**Comment by MarianBlanco** [comment]
Hola de nuevo... ¿Cómo va este punto? Elisa y yo estamos preocupadas porque sin que sea responsive no se puede lanzar nada... :S 

Si el chico que estaba ayudando se ha bajado del carro... ¿podéis echarnos una mano @ferblape @flowsta o alguien que esté colaborando en otros proyectos?

**Comment by ferblape** [comment]
Hola,

Yo es que no sé nada de responsive, lo siento. Os podría presentar a
alguien que se pueda encargar, aunque claro, tiene otras tarifas, aunque
todo es hablarlo. Adolfo?

2016-03-01 11:23 GMT+01:00 MarianBlanco notifications@github.com:

**Comment by flowsta** [comment]
No lo había visto. Una pregunta, qué detectais que no es responsive además del menú. Y una duda, el trabajo que hizo con el menú, valió en algún momento. Hay una opción fácil, volver al punto 0, con el menú kebab. Otra opción que creo que comenté y no sé cuánto llevaría, adaptar el menú de otro tema. Qué decís?

**Comment by MarianBlanco** [comment]
El problema no es que el menú no es responsive... Es que la web no es responsive al 100% porque desde el móvil únicamente me ha salido correctamente la sección de entrevistas. Mismamente en la home hay muchas partes que se cortan, los gráficos ni se ven... y  por ejemplo la "estrella" del proyecto que es la herramienta que también se ven mal desde el móvil. 

Adjunto pantallazos en esta carpeta: https://drive.google.com/folderview?id=0Bx5FSR7-5gMcVmZmb25KM2sycTg&usp=sharing

Son de la home, herramienta, gráficos y contacto...

**Comment by flowsta** [comment]
A ver si podemos resolver esto...

**Comment by MarianBlanco** [comment]
El problema es solo desde el móvil, con la tablet o ipad se ve bien. Pero claro... el acceso a través del smartphone ronda el 90%, vamos cualquiera de nosotrxs somos un ejemplo de ello. ¿Cómo lo podemos hacer? 
Temo que con las noticias de los últimos días en Grecia y la reunión de la UE del lunes, desde El Confidencial nos digan que es una buena percha para sacar la web, los gráficos, la herramienta y los reportajes... Y claro... viéndose así desde el móvil se desluce todo el curro mucho no?

**Comment by elisagpaleo** [comment]
Hola a todxs!

Ayer @maritrinez @MarianBlanco y yo nos reunimos para decidir algunas cosas sobre la web y nos preguntábamos @flowsta si habéis conseguido dar con alguien que pueda echarle una mano a Bea con el tema de hacer el site responsive.

Mil gracias!!!!

**Comment by iamsortiz** [comment]
Buenas, ya he comentado en un pull-request que no me va a resultar posible echaros una mano, pero os dejo la rama de código con la intentona que estaba sacando adelante
- https://github.com/iamsortiz/3tpd-asilo-ue/commits/iamsortiz-try-responsive

En dicha rama [este commit](https://github.com/iamsortiz/3tpd-asilo-ue/commit/f160a438ac34a5eb1c1a304d323aef011fe89f11) es en el que ya había puesto [componente navbar de Bootstrap](http://getbootstrap.com/components/#navbar), para tener el nav superior responsive.

La idea era partir de 0 usando los estilos de vuestra plantilla para todas las secciones menos las de las visualizaciones (es mas movida de hacer responsive) y usando Bootstrap para hacer responsive la web (por que es "sencillo" y esta extendido)

Si algún desarrollador quiere seguir intentando por la vía del bootstrap navbar aqui tiene el [css adaptado a vuestra template](https://github.com/iamsortiz/3tpd-asilo-ue/blob/iamsortiz-try-responsive/style/css/bootstrap_nav.css) generado con: http://work.smarchal.com/twbscolor/

Y tambien un ["hack"](https://github.com/iamsortiz/3tpd-asilo-ue/blob/iamsortiz-try-responsive/style/css/bootstrap_navbar_breakpoint.css) para que evitar que el navbar se ponga a 2 columnas dado que hay mucho texto en el mismo (consiste en solo mostrar todo el texto del nav si hay mas de "X" pixeles de ancho, si no, mostrar la versión movil. es una chapuza pero para tanto texto es lo único que se me ocurría)
