### ISSUE TITLE
Gráficos de España para El Confidencial 

### ISSUE THREAD

**Issue by MarianBlanco** [medialab-prado/3tpd-asilo-ue#21]
@maritrinez Creo que ya lo comentó @elisagpaleo en la reunión pero como no está aquí registrado igual se nos pasa. 

Hay que los gráficos que tenemos únicamente con los datos de España o en su defecto pasarles los datos a El Confidencial (nos dijeron que por su parte no había problema si estabas muy liada). 

Creo que en el de los países sería importante incluir los "apátridas" ya que he visto en los informes de Interior que se conceden bastante a Palestina, y viendo que hay algunxs refugiadxs de Siria que eran a su vez refugiadxs de Palestina en Siria (es justo el caso del protagonista del relato)... Estaría bien para el reportaje.

**Comment by maritrinez** [comment]
Os paso los datos, no tengo tiempooo!

**Comment by maritrinez** [comment]
Datos y gráficos enviados!
