### ISSUE TITLE
Compartir en redes sociales

### ISSUE THREAD

**Issue by ferblape** [medialab-prado/3tpd-asilo-ue#6]

**Comment by MarianBlanco** [comment]
No sé qué otras cosas se podrían hacer, pero me gusta el modelo que tienen en esta página de colocarlo en la parte superior derecha: http://www.bajatelapotencia.org/

**Comment by ferblape** [comment]
Mirad, lo he puesto sólo en la home y al mostrar los resultados de la herramienta. Algún sitio más?

**Comment by MarianBlanco** [comment]
Yo creo que (si entendí bien) la idea era compartir también los resultados del "Ponte en su lugar" no?

**Comment by ferblape** [comment]
A eso me refiero con lo de la herramienta. Se muestra lo de compartir en redes sociales después de seleccionar los 4 parámetros y ver los resultados.

**Comment by MarianBlanco** [comment]
Ok! Ahora lo he visto. Lo único que me surge una duda ¿se podría cambiar el texto que sale por defecto? 
En lugar de "Asilo en la UE - Predict - ¿Y tú?" que apareciera "La probabilidad de que reciba asilo en... ¡Ponte en su lugar! #EuropaSinRefugio"

**Comment by ferblape** [comment]
Ya está cambiado :+1:
